Add endpoint_override parameter to python-magnumclient
When trying to consume python-magnumclient from os-cloud-config,
it is failing with:

TypeError: __init__() got an unexpected keyword argument 'endpoint_override'

That is because this parameter is not supported in v1 from magnumclient. Add the
parameter, forcing to be the equivalent of magnum_url.

Change-Id: I3e9d41c3efabf23826f35fc8d1bb12c14770460b
Closes-Bug: 1573468