Make --cluster option required for ca-rotate
Otherwise, the following error with be shown:

$ magnum ca-rotate
ERROR: 'Namespace' object has no attribute 'bay'

Change-Id: I48c19ad585d3bcb863c5432fae6a6c8af358a21b
Closes-Bug: #1677393