Prevent list rcs when bay is not ready
Prevent list rcs when bay is not ready, otherwise it will return:
$ magnum rc-list --bay k8sbay
ERROR: unsupported operand type(s) for +: 'NoneType' and 'str' (HTTP 500)

Which makes no sense.

Also added unit test for this case.

Change-Id: Ib869f6e9a187a3e99a2e38ea19b882c87c195726